# Generated by Django 5.2.11 on 2026-03-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(default=0)),
                ('satisfactory', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
            ],
        ),
    ]
